version: '3.8'

x-common:
  &common
  env_file: .env

services:

  app:
    <<: *common
    build: .
    container_name: app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    container_name: ${MONGO_SERVER}
    restart: always
    environment:
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_DATA_DIR=${MONGODB_DATA_DIR}
      - MONGODB_LOG_DIR=${MONGODB_LOG_DIR}
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping')" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_SERVER}  # same as mongo container name
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "${ME_CONFIG_HTTP_PORT}:8081"
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge