name: Новое ТЗ
author: bogdan@ogurkova_castorama.com
description: |
  ОЧЕНЬ ВАЖНО!!! 
  Все события, особенно GA:pageview должны отрабатывать после загрузки GTM DOM, 
  в противном случае не будет слушателей разметки и данные уйдут в пустоту.
  
  События следует отправлять на уровень document (НЕ document.body) и генерировать их через dispatchEvent.
  Также необходимо добавить логирование в консоль, если enabledLogAnalytics = 1
  
  При клике на кнопку или ссылку (clickButton, clickProduct, promoClick) - учитывать
  все клики, которые приводят к переходу - левой кнопкой мыши, по колесику мыши.
blocks: []